version: "3"
services:
  mysql:
    image: souhub/avzeus-mysql_dev:1.1
    ports:
      - "3306:3306"

  backend:
    image: souhub/avzeus-backend:1.6
    depends_on:
      - mysql
    environment:
      - DB_USER=souhub
      - DB_PASS=devpass
      - DB_PROTOCOL=tcp
      - DB_ENDPOINT=mysql:3306
      - DB_NAME=avzeus
      - CLOUD_STORAGE_PATH=https://storage.googleapis.com/avzeus
      - BACKEND_URL=http://backend:8000
      - AI_URL=http://ai:5000
    ports:
      - "8000:8000"

  ai:
    image: souhub/avzeus-ai:1.3
    tty: true
    ports:
      - "5000:5000"

  frontend:
    image: souhub/avzeus-frontend:1.3
    tty: true
    depends_on:
      - mysql
      - backend
      - ai
    ports:
      - "8080:80"
